### ISSUE TITLE
How can I rendre the svg without the corners

### ISSUE THREAD

**Issue by elbanyaoui** [vladrub/SVG-image-editor#1]
Hello,

Thank you for this script,

I want to know how can I render the svg code without the corners,
 I tried imageEditor.render().el but the result contain layers with corners (see attached Image )

![7-30-2015 11-37-16 am](https://cloud.githubusercontent.com/assets/10333690/8982376/2bb8ede2-36b0-11e5-86c0-6bff8571809b.png)

Best regards

**Comment by vladrub** [comment]
@elbanyaoui hello!

Just try to hide them

.resizable-group, .rotatable-group, .draggable-handle { display: none; }

**Comment by elbanyaoui** [comment]
Thank you
